#!/usr/bin/env python3
"""Generate EZRA_COMMANDS.md from Ezra's maintained command catalog."""

from pathlib import Path
import textwrap


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "EZRA_COMMANDS.md"


PRESENTATION_COMMANDS = (
    ("Introduce yourself", "Reads Ezra's introduction.", "Yes"),
    ("Tell us who you are", "Reads Ezra's introduction.", "Yes"),
    ("Where does your name come from?", "Explains how Ezra got his name.", "Yes"),
    ("Start the presentation", "Opens the Acts presentation at slide 1.", "Yes"),
    (
        "Start the presentation on slide 5",
        "Opens the presentation at the requested slide.",
        "Yes",
    ),
    ("Next slide / Forward", "Moves to the next slide.", "Yes"),
    ("Previous slide / Back", "Moves to the previous slide.", "No"),
    (
        "Go to slide 4 / Show us slide 4 of the presentation",
        "Displays a numbered slide.",
        "No*",
    ),
    ("Show question 2", "Displays the requested question slide.", "No*"),
    ("Reveal the answer / Show the answers", "Reveals the answer slide.", "Yes"),
    ("Display the answers", "Reveals the answers without reading them.", "No*"),
    (
        "Tell us about this slide / Explain this slide",
        "Reads the script for the displayed slide.",
        "Yes",
    ),
    ("Stop the presentation", "Closes the presentation.", "No"),
    (
        "Rehearse the presentation / Preview the presentation / Test the presentation",
        "Prints a complete rehearsal without slides or speech.",
        "No",
    ),
    (
        "Question about the current Acts lessons",
        "Searches all presentation-folder JSONL study-book files and Scripture.",
        "Yes",
    ),
    (
        "Tell us more",
        "Continues the previous sourced answer with the next relevant point.",
        "Yes",
    ),
    (
        "Give us your own broader explanation of ...",
        "Bypasses study-book and Scripture retrieval for a brief general explanation.",
        "Yes",
    ),
    (
        "Outside of Scripture, what ...?",
        "Requests Ezra's own broader, non-scriptural explanation.",
        "Yes",
    ),
)

BIBLE_COMMANDS = (
    ("John 3:16", "Reads one verse."),
    ("Read John chapter 3", "Reads a chapter, subject to the spoken-verse limit."),
    ("Romans 8:28 through 30", "Reads a range of verses."),
    ("First Peter 2 verse 9", "Understands numbered Bible books."),
    ("Now read verse 10", "Continues using the most recently requested Bible book."),
)

OTHER_COMMANDS = (
    ("What time is it?", "Speaks the current local time."),
    ("Set volume to 1–10", "Sets speaker volume from 10% to 100%."),
    ("What's the weather?", "Reports weather for the configured location."),
    ("What's the weather in Dallas?", "Reports weather for a named location."),
    ("What is the forecast? / Will it rain?", "Reports relevant forecast details."),
    ("What's the news? / Read the headlines", "Reports current news headlines."),
    ("Ezra, stop", "Interrupts Ezra while he is speaking."),
    ("Quit / Exit / Stop program", "Exits the Ezra application."),
    ("Shutdown / Power off", "Exits Ezra and attempts to power off the Pi."),
    (
        "Any general question",
        "Uses Ezra's AI; recent conversation can provide follow-up context.",
    ),
)


def _table(headers, rows):
    """Render stable-width columns with alternatives on continuation rows."""
    widths = (52, 70, 9) if len(headers) == 3 else (38, 70)

    def formatted_row(values):
        return "| " + " | ".join(
            str(value).ljust(widths[index])
            for index, value in enumerate(values)
        ) + " |"

    lines = [
        formatted_row(headers),
        formatted_row(tuple("-" * width for width in widths)),
    ]
    for row in rows:
        commands = str(row[0]).split(" / ")
        descriptions = textwrap.wrap(
            str(row[1]),
            width=70,
            break_long_words=False,
            break_on_hyphens=False,
        ) or [""]
        continuation_count = max(len(commands), len(descriptions))
        for index in range(continuation_count):
            command = commands[index] if index < len(commands) else ""
            if index > 0 and command:
                command = f"    {command}"
            description = descriptions[index] if index < len(descriptions) else ""
            trailing = row[2:] if index == 0 else tuple("" for _item in row[2:])
            lines.append(formatted_row((command, description, *trailing)))
    return "\n".join(lines)


def render_reference():
    return f"""# Ezra Command Reference

<!-- Generated by tools/build_command_reference.py. Do not edit by hand. -->

Begin each interaction with **“Ezra”** or **“Hey Ezra.”** The examples below
show natural phrases; minor wording variations are accepted.

## Presentation commands

{_table(("Command", "What it does", "Narrates?"), PRESENTATION_COMMANDS)}

\\* Add **“and explain”** to a non-narrating slide, question, or answer-display
command to read the script after displaying it. For example: **“Go to slide 4
and explain.”** These variations are not listed separately.

If a valid presentation command is given before the presentation is running,
Ezra starts the presentation silently and immediately performs that command.

## Bible commands

{_table(("Command", "What it does"), BIBLE_COMMANDS)}

Ezra uses the NIV when it is available online and the local World English Bible
when offline. A Bible passage can also be displayed while Ezra reads it.

## Other commands

{_table(("Command", "What it does"), OTHER_COMMANDS)}

## Notes

- Lesson questions search every `.jsonl` file in `presentations/`; added or
  modified files are detected automatically.
- Sourced answers identify the study book or Scripture. PowerPoint speaker
  notes are used for slide narration only and are not question-answer sources.
- Ezra initially gives the most relevant sourced point in no more than two
  short sentences. If more relevant material remains, Ezra says **“There is
  more.”** Say **“Ezra, tell us more”** to continue the original answer.
- Requests for Ezra's own broader explanation bypass lesson and Scripture
  retrieval and are identified as Ezra's own explanation.
- Weather, news, and online AI responses require an internet connection.
- When offline, general questions use Ezra's local AI if it is available.
- Say **“Ezra, stop”** during speech to interrupt the response; this does not
  exit the application.
- Ezra enters sleep mode after the configured inactivity period. Say **“Ezra”**
  or **“Hey Ezra”** to wake him.
- Volume control and system shutdown depend on operating-system permissions.
"""


def main():
    OUTPUT_PATH.write_text(render_reference(), encoding="utf-8")
    print(f"Updated {OUTPUT_PATH.name}")


if __name__ == "__main__":
    main()
